name: Integration tests

on:
  pull_request:
    branches: [master, dev]

jobs:
  # postgres:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [8.x, 10.x, 12.x]

  #   services:
  #     postgres:
  #       image: postgres
  #       env:
  #         POSTGRES_PASSWORD: postgres
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #       ports:
  #         # Maps tcp port 5432 on service container to the host
  #         - 5432:5432

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm install
  #     - run: npm test
  #       env:
  #         CI: true
  #         PORT: 6000
  #         DB_HOST: localhost
  #         DB_USER: postgres
  #         DB_PW: postgres
  #         DB_DIALECT: postgres
  #         DB_DATABASE: postgres

  mysql: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          # mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
          mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'test'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          CI: true
          PORT: 6000
          DB_HOST: localhost
          DB_USER: developer
          DB_PW: test
          DB_DIALECT: mysql
          DB_DATABASE: some_test